
/* Ver.0.45 temporary demo seed: only runs on a completely empty install */
(function seedCarLogDemo(){
  try{
    const hasAny =
      localStorage.getItem("carlog_vehicle") ||
      localStorage.getItem("carlog_vehicles") ||
      localStorage.getItem("fuelRecords") ||
      localStorage.getItem("carlog_maintenance") ||
      localStorage.getItem("carlog_expenses");
    if(hasAny) return;
    const vid="demo-freed";
    const vehicle={id:vid,name:"Honda FREED",maker:"Honda",model:"GP3",year:"2014",color:"ホワイト",
      odometer:38842,inspectionDate:"2027-06-15",oilInterval:5000,plate:"",photoId:null,memos:[]};
    localStorage.setItem("carlog_vehicle",JSON.stringify(vehicle));
    localStorage.setItem("carlog_vehicles",JSON.stringify([vehicle]));
    localStorage.setItem("carlog_active_vehicle",vid);
    const fuel=[
      {id:"df1",vehicleId:vid,date:"2026-09-20",time:"15:30",odometer:38842,liters:39.6,store:"ENEOS",amount:6280,fullTank:true,distance:626,fuelEconomy:15.8,pricePerLiter:158.6,createdAt:"2026-09-20T15:30:00"},
      {id:"df2",vehicleId:vid,date:"2026-08-20",time:"16:10",odometer:38216,liters:40.2,store:"コスモ石油",amount:6650,fullTank:true,distance:647,fuelEconomy:16.1,pricePerLiter:165.4,createdAt:"2026-08-20T16:10:00"},
      {id:"df3",vehicleId:vid,date:"2026-07-18",time:"11:20",odometer:37569,liters:38.8,store:"ENEOS",amount:6360,fullTank:true,distance:605,fuelEconomy:15.6,pricePerLiter:163.9,createdAt:"2026-07-18T11:20:00"}
    ];
    const maint=[
      {id:"dm1",vehicleId:vid,date:"2026-09-12",time:"10:00",type:"オイル交換",odometer:38620,amount:4800,store:"カーショップ",memo:"エンジンオイル交換"},
      {id:"dm2",vehicleId:vid,date:"2026-08-28",time:"13:00",type:"タイヤ交換",odometer:37100,amount:28400,store:"タイヤショップ",memo:"後輪2本交換"}
    ];
    const exp=[
      {id:"de1",vehicleId:vid,date:"2026-09-05",time:"14:00",category:"洗車",amount:1200,store:"洗車場",memo:"手洗い洗車"},
      {id:"de2",vehicleId:vid,date:"2026-08-10",time:"09:00",category:"その他",amount:1400,store:"",memo:"車用品"}
    ];
    localStorage.setItem("fuelRecords",JSON.stringify(fuel));
    localStorage.setItem("carlog_maintenance",JSON.stringify(maint));
    localStorage.setItem("carlog_expenses",JSON.stringify(exp));
    localStorage.setItem("carlog_demo_seed_v045","1");
  }catch(e){console.warn("demo seed skipped",e)}
})();

const KEY={vehicles:"carlog_vehicles",active:"carlog_active_vehicle",legacy:"carlog_vehicle",fuel:"fuelRecords",maint:"carlog_maintenance",expense:"carlog_expenses"};
const load=(k,d)=>{try{let v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=p=>p+"_"+(crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random().toString(16).slice(2));
const today=()=>{let d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},nowTime=()=>new Date().toTimeString().slice(0,5),nf=v=>Number(v||0).toLocaleString("ja-JP"),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let vehicles=load(KEY.vehicles,[]),activeId=localStorage.getItem(KEY.active)||"",fuelRecords=load(KEY.fuel,[]),maintenanceRecords=load(KEY.maint,[]),expenseRecords=load(KEY.expense,[]);
let edit={fuel:null,maintenance:null,expense:null,vehicle:null},costYear=new Date().getFullYear(),costChartMode="total",driveMode="distance",pendingVehiclePhoto=null,memoDraft=[];
const COLOR_LABELS={white:"ホワイト",black:"ブラック",silver:"シルバー",gray:"グレー",red:"レッド",blue:"ブルー",navy:"ネイビー",green:"グリーン",beige:"ベージュ",brown:"ブラウン",yellow:"イエロー",orange:"オレンジ",purple:"パープル",other:"その他"};
const COLOR_HEX={white:"#f4f4f2",black:"#25282d",silver:"#b8bdc5",gray:"#737982",red:"#c93c3c",blue:"#3478c8",navy:"#263f68",green:"#4f7d57",beige:"#d5c4a1",brown:"#795548",yellow:"#e5bf36",orange:"#df7b2c",purple:"#76518d",other:"#8b95a5"};
function carSvg(color){let fill=COLOR_HEX[color]||"#8b95a5";return `<svg viewBox="0 0 180 90"><path fill="${fill}" stroke="#333" stroke-width="3" d="M20 58l12-25c3-7 9-11 17-11h72c9 0 16 4 21 11l17 25 8 5v11H12V64z"/><path fill="#dce8ef" d="M49 29h30v24H38l9-20zm38 0h32c7 0 11 3 15 9l10 15H87z"/><circle cx="47" cy="72" r="12" fill="#24272c"/><circle cx="137" cy="72" r="12" fill="#24272c"/></svg>`}


function migrate(){let legacy=load(KEY.legacy,null);if(!vehicles.length&&legacy){vehicles=[legacy];save(KEY.vehicles,vehicles);activeId=legacy.id;localStorage.setItem(KEY.active,activeId)}if(!activeId&&vehicles[0]){activeId=vehicles[0].id;localStorage.setItem(KEY.active,activeId)}if(vehicles.length===1){[fuelRecords,maintenanceRecords,expenseRecords].forEach(a=>a.forEach(r=>{if(!r.vehicleId)r.vehicleId=vehicles[0].id}));persistRecords()}}
function persistRecords(){save(KEY.fuel,fuelRecords);save(KEY.maint,maintenanceRecords);save(KEY.expense,expenseRecords)}
const car=()=>vehicles.find(v=>v.id===activeId)||null,fuels=()=>fuelRecords.filter(r=>r.vehicleId===activeId),maints=()=>maintenanceRecords.filter(r=>r.vehicleId===activeId),expenses=()=>expenseRecords.filter(r=>r.vehicleId===activeId);
function stamp(r){return(r.date||"")+"T"+(r.time||"00:00")+":"+(r.createdAt||"")}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");let hide=id==="setup";bottomNav.classList.toggle("hidden",hide);adDock.classList.toggle("hidden-ad",hide)}
document.addEventListener("DOMContentLoaded",()=>{migrate();refreshStoreNames();car()?goHome():show("setup")});

function currentKm(){let c=car();return Math.max(Number(c?.odometer)||0,...fuels().map(r=>+r.odometer||0),...maints().map(r=>+r.odometer||0))}
function createVehicleFromSetup(){let n=setupName.value.trim(),km=+setupKm.value;if(!n||km<0)return alert("車両名と走行距離を入力してください。");let v={id:uid("vehicle"),name:n,maker:setupMaker.value.trim(),odometer:km,inspectionDate:setupInspection.value,oilInterval:+setupOil.value||5000,createdAt:new Date().toISOString(),memos:[]};vehicles.push(v);activeId=v.id;save(KEY.vehicles,vehicles);localStorage.setItem(KEY.active,activeId);goHome()}
function goHome(){edit.fuel=edit.maintenance=edit.expense=null;if(!car())return show("setup");show("home");renderHome()}
function costs(y,m){let same=r=>{let d=(r.date||"").split("-").map(Number);return d[0]===y&&(!m||d[1]===m)},f=fuels().filter(same).reduce((s,r)=>s+(+r.amount||0),0),mt=maints().filter(same).reduce((s,r)=>s+(+r.amount||0),0),e=expenses().filter(same).reduce((s,r)=>s+(+r.amount||0),0);return{fuel:f,maint:mt,other:e,total:f+mt+e}}
function recomputeFuel(){let rs=fuels().sort((a,b)=>+a.odometer-+b.odometer||stamp(a).localeCompare(stamp(b)));rs.forEach((r,i)=>{let p=rs[i-1];r.distance=p?+r.odometer-+p.odometer:null;r.fuelEconomy=p&&r.fullTank&&p.fullTank&&r.distance>0?r.distance/+r.liters:null;r.pricePerLiter=+r.liters?+r.amount/+r.liters:null});save(KEY.fuel,fuelRecords)}
async function renderHome(){let c=car(),km=currentKm();c.odometer=km;save(KEY.vehicles,vehicles);homeCarName.textContent=c.name;homeMaker.textContent=c.maker||"";homeCarMeta.textContent=[c.model,c.year,COLOR_LABELS[c.color]||c.color].filter(Boolean).join(" / ");homeKm.textContent=nf(km)+" km";renderCarThumb(c);
let d=new Date(),y=d.getFullYear(),m=d.getMonth()+1,mc=costs(y,m);monthFuel.textContent=nf(mc.fuel)+" 円";monthTotal.textContent=nf(mc.total)+" 円";let md=monthDrive(y,m);monthKm.textContent=nf(Math.round(md.distance))+" km";let eco=fuels().filter(r=>+r.fuelEconomy>0).sort((a,b)=>stamp(b).localeCompare(stamp(a)))[0];latestEco.textContent=eco?(+eco.fuelEconomy).toFixed(1)+" km/L":"記録なし";
let yc=costs(y),elapsed=m;yearTotal.textContent=nf(yc.total)+" 円";yearAvg.textContent=nf(Math.round(yc.total/elapsed))+" 円";let yd=Array.from({length:12},(_,i)=>monthDrive(y,i+1).distance).reduce((a,b)=>a+b,0);yearKm.textContent=nf(Math.round(yd))+" km";perKm.textContent=yd?(yc.total/yd).toFixed(1)+" 円/km":"---";
if(c.inspectionDate){inspection.textContent=c.inspectionDate.replaceAll("-","/");let days=Math.ceil((new Date(c.inspectionDate+"T00:00:00")-new Date(today()+"T00:00:00"))/86400000);inspectionLeft.textContent=days>=0?"あと "+nf(days)+" 日":"期限切れ"}else{inspection.textContent="未設定";inspectionLeft.textContent=""}
let oil=maints().filter(r=>["オイル交換","オイル＋フィルター交換"].includes(r.type)).sort((a,b)=>+b.odometer-+a.odometer)[0];if(c.oilInterval){let target=(oil?+oil.odometer:km)+(+c.oilInterval);oilTarget.textContent=nf(target)+" km";let left=target-km;oilLeft.textContent=left>=0?"あと "+nf(left)+" km":nf(Math.abs(left))+" km超過"}else{oilTarget.textContent="未設定";oilLeft.textContent=""}
let all=allRecords().slice(0,5);recent.innerHTML=all.length?all.map(historyHtml).join(""):'<p class="help">まだ記録がありません。中央の＋から追加できます。</p>';renderHomeMemos(c)}
async function renderCarThumb(c){homeCarThumb.innerHTML=carSvg(c.color);if(c.photoId){let rec=await imageGet(c.photoId);if(rec){let u=URL.createObjectURL(rec.blob);homeCarThumb.innerHTML=`<img src="${u}" onload="URL.revokeObjectURL(this.src)">`}}}
function allRecords(){let a=[];fuels().forEach(r=>a.push({...r,_kind:"fuel",_title:"給油",_detail:[r.store,r.liters?`${r.liters} L`:""].filter(Boolean).join(" ・ ")}));maints().forEach(r=>a.push({...r,_kind:"maintenance",_title:r.type||"整備・修理",_detail:[r.store,r.memo].filter(Boolean).join(" ・ ")}));expenses().forEach(r=>a.push({...r,_kind:"expense",_title:r.category||"その他支出",_detail:[r.store,r.memo].filter(Boolean).join(" ・ ")}));return a.sort((a,b)=>stamp(b).localeCompare(stamp(a)))}
function historyHtml(r){return`<div class="recent-row"><div><b>${esc(r._title)}</b><small>${esc(r.date||"")} ${esc(r.time||"")} ${r._detail?"・ "+esc(r._detail):""}</small></div><b>${nf(r.amount)} 円</b></div>`}
function storeNamesList(){return [...new Set([...fuelRecords,...maintenanceRecords,...expenseRecords].map(r=>(r.store||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"))}
function refreshStoreNames(){["fuel","maint","expense"].forEach(p=>populateStoreSelect(p))}
function populateStoreSelect(p,current=""){let el=document.getElementById(p+"StoreSelect");if(!el)return;let names=storeNamesList();el.innerHTML='<option value="">店名を選択</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("")+'<option value="__new__">新しい店名を入力</option>';let inp=document.getElementById(p+"Store");if(current&&names.includes(current)){el.value=current;inp.value=current}else if(current){el.value="__new__";inp.value=current}else{el.value="";inp.value=""}}
function chooseStore(p){let s=document.getElementById(p+"StoreSelect"),i=document.getElementById(p+"Store");if(s.value==="__new__"){i.value="";i.focus()}else i.value=s.value}

function openFuel(id=null){edit.fuel=id;let r=id?fuelRecords.find(x=>x.id===id):null;fuelTitle.textContent=r?"給油記録を編集":"給油を記録";fuelSave.textContent=r?"変更を保存":"登録";fuelDelete.classList.toggle("hidden",!r);fuelDate.value=r?.date||today();fuelTime.value=r?.time||nowTime();fuelKm.value=r?.odometer??currentKm();fuelLiters.value=r?.liters??"";populateStoreSelect("fuel",r?.store||"");fuelAmount.value=r?.amount??"";fuelFull.checked=r?.fullTank??true;show("fuel");showSameDay("fuel")}
function saveFuel(){let r={date:fuelDate.value,time:fuelTime.value||"00:00",odometer:+fuelKm.value,liters:+fuelLiters.value,store:fuelStore.value.trim(),amount:+fuelAmount.value,fullTank:fuelFull.checked};if(!r.date||r.odometer<0||r.liters<=0||r.amount<=0)return alert("入力内容を確認してください。");if(edit.fuel){let i=fuelRecords.findIndex(x=>x.id===edit.fuel);fuelRecords[i]={...fuelRecords[i],...r}}else fuelRecords.push({id:uid("fuel"),vehicleId:activeId,...r,createdAt:new Date().toISOString()});persistRecords();recomputeFuel();refreshStoreNames();goHome()}
function openMaintenance(id=null){edit.maintenance=id;let r=id?maintenanceRecords.find(x=>x.id===id):null;maintTitle.textContent=r?"整備・修理を編集":"整備・修理を記録";maintSave.textContent=r?"変更を保存":"登録";maintDelete.classList.toggle("hidden",!r);maintDate.value=r?.date||today();maintTime.value=r?.time||nowTime();maintType.value=r?.type||"オイル交換";maintKm.value=r?.odometer??currentKm();maintAmount.value=r?.amount??"";populateStoreSelect("maint",r?.store||"");maintMemo.value=r?.memo||"";show("maintenance");showSameDay("maintenance")}
function saveMaintenance(){let r={date:maintDate.value,time:maintTime.value||"00:00",type:maintType.value,odometer:+maintKm.value,amount:+maintAmount.value||0,store:maintStore.value.trim(),memo:maintMemo.value.trim()};if(!r.date||r.odometer<0||r.amount<0)return alert("入力内容を確認してください。");if(edit.maintenance){let i=maintenanceRecords.findIndex(x=>x.id===edit.maintenance);maintenanceRecords[i]={...maintenanceRecords[i],...r}}else maintenanceRecords.push({id:uid("maintenance"),vehicleId:activeId,...r,createdAt:new Date().toISOString()});persistRecords();refreshStoreNames();goHome()}
function openExpense(id=null){edit.expense=id;let r=id?expenseRecords.find(x=>x.id===id):null;expenseTitle.textContent=r?"その他支出を編集":"その他支出を記録";expenseSave.textContent=r?"変更を保存":"登録";expenseDelete.classList.toggle("hidden",!r);expenseDate.value=r?.date||today();expenseTime.value=r?.time||nowTime();expenseCategory.value=r?.category||"自動車税";expenseAmount.value=r?.amount??"";populateStoreSelect("expense",r?.store||"");expenseMemo.value=r?.memo||"";show("expense");showSameDay("expense")}
function saveExpense(){let r={date:expenseDate.value,time:expenseTime.value||"00:00",category:expenseCategory.value,amount:+expenseAmount.value,store:expenseStore.value.trim(),memo:expenseMemo.value.trim()};if(!r.date||r.amount<=0)return alert("日付と金額を入力してください。");if(edit.expense){let i=expenseRecords.findIndex(x=>x.id===edit.expense);expenseRecords[i]={...expenseRecords[i],...r}}else expenseRecords.push({id:uid("expense"),vehicleId:activeId,...r,createdAt:new Date().toISOString()});persistRecords();refreshStoreNames();goHome()}
function deleteCurrent(kind){let id=edit[kind];if(!id||!confirm("この記録を削除しますか？"))return;if(kind==="fuel")fuelRecords=fuelRecords.filter(x=>x.id!==id);if(kind==="maintenance")maintenanceRecords=maintenanceRecords.filter(x=>x.id!==id);if(kind==="expense")expenseRecords=expenseRecords.filter(x=>x.id!==id);persistRecords();if(kind==="fuel")recomputeFuel();refreshStoreNames();goHome()}
function showSameDay(kind){let date=kind==="fuel"?fuelDate.value:kind==="maintenance"?maintDate.value:expenseDate.value,box=kind==="fuel"?fuelSameDay:kind==="maintenance"?maintSameDay:expenseSameDay,arr=kind==="fuel"?fuels():kind==="maintenance"?maints():expenses(),rs=arr.filter(r=>r.date===date).sort((a,b)=>stamp(a).localeCompare(stamp(b)));if(!rs.length){box.innerHTML="";return}box.innerHTML=`<div class="samebox"><small>この日の登録済み記録 ${rs.length}件</small>${rs.map(r=>`<div class="same-item"><div><b>${esc(r.time||"--:--")} ${kind==="fuel"?esc((r.liters||0)+" L / "+nf(r.amount)+"円"):kind==="maintenance"?esc(r.type+" / "+nf(r.amount)+"円"):esc(r.category+" / "+nf(r.amount)+"円")}</b></div><button type="button" onclick="${kind==="fuel"?"openFuel":kind==="maintenance"?"openMaintenance":"openExpense"}('${r.id}')">編集</button></div>`).join("")}</div>`}

function openHistory(){show("history");renderHistory("all")}function renderHistory(filter){let rs=allRecords().filter(r=>filter==="all"||r._kind===filter);historyList.innerHTML=rs.length?rs.map(r=>`<button class="card menu" onclick="${r._kind==="fuel"?"openFuel":r._kind==="maintenance"?"openMaintenance":"openExpense"}('${r.id}')"><div><b>${esc(r._title)}</b><small>${esc(r.date)} ${esc(r.time||"")} ・ ${nf(r.amount)}円${r.store?" ・ "+esc(r.store):""}</small></div><span>編集 ›</span></button>`).join(""):'<div class="card">記録はありません。</div>'}

function openCosts(mode){if(mode)costChartMode=mode;show("costs");renderCosts()}function changeYear(n){costYear+=n;renderCosts()}function setCostChart(m){costChartMode=m;renderCostChart()}
function renderCosts(){costYearEl=document.getElementById("costYear");costYearEl.textContent=costYear+"年";let c=costs(costYear),months=costYear===new Date().getFullYear()?new Date().getMonth()+1:12;costTotal.textContent=nf(c.total)+" 円";costFuel.textContent=nf(c.fuel)+" 円";costMaint.textContent=nf(c.maint)+" 円";costOther.textContent=nf(c.other)+" 円";costAvg.textContent=nf(Math.round(c.total/months))+" 円";renderCostChart()}
function renderCostChart(){let labels={total:"年間合計",fuel:"ガソリン",maint:"整備・維持",other:"その他",avg:"月平均"};["total","fuel","maint","other","avg"].forEach(k=>document.getElementById("costCard"+({total:"Total",fuel:"Fuel",maint:"Maint",other:"Other",avg:"Avg"}[k])).classList.toggle("active",costChartMode===k));monthChartTitle.textContent=costChartMode==="avg"?"月ごとの累計平均":"月別 "+labels[costChartMode];let vals;if(costChartMode==="avg"){let now=new Date(),currentYear=now.getFullYear(),lastMonth=costYear<currentYear?12:costYear===currentYear?now.getMonth()+1:0,run=0;vals=Array.from({length:12},(_,i)=>{let month=i+1;if(month>lastMonth)return null;run+=costs(costYear,month).total;return run/month})}else vals=Array.from({length:12},(_,i)=>costs(costYear,i+1)[costChartMode]);renderBars(monthBars,vals,"円")}

function monthDrive(y,m){let key=`${y}-${String(m).padStart(2,"0")}`,rs=fuels().filter(r=>r.date?.startsWith(key)).sort((a,b)=>stamp(a).localeCompare(stamp(b))),liters=rs.reduce((s,r)=>s+(+r.liters||0),0),amount=rs.reduce((s,r)=>s+(+r.amount||0),0),distance=rs.reduce((s,r)=>s+(+r.distance>0?+r.distance:0),0),ecos=rs.filter(r=>+r.fuelEconomy>0).map(r=>+r.fuelEconomy);return{distance,liters,count:rs.length,economy:ecos.length?ecos.reduce((a,b)=>a+b,0)/ecos.length:0,price:liters?amount/liters:0,fuelkm:distance?amount/distance:0}}
function openDriving(mode){if(mode)driveMode=mode;show("driving");renderDriving()}function setDriveChart(m){driveMode=m;renderDriving()}
function renderDriving(){let y=new Date().getFullYear(),vals=Array.from({length:12},(_,i)=>monthDrive(y,i+1)),sum=k=>vals.reduce((s,x)=>s+x[k],0),lit=sum("liters"),dist=sum("distance"),amount=costs(y).fuel,eco=vals.filter(x=>x.economy).map(x=>x.economy);driveDistance.textContent=nf(Math.round(dist))+" km";driveLiters.textContent=lit.toFixed(1)+" L";driveCount.textContent=nf(sum("count"))+" 回";driveEconomy.textContent=eco.length?(eco.reduce((a,b)=>a+b,0)/eco.length).toFixed(1)+" km/L":"---";drivePrice.textContent=lit?(amount/lit).toFixed(1)+" 円/L":"---";driveFuelKm.textContent=dist?(amount/dist).toFixed(1)+" 円/km":"---";let map={distance:["Distance","走行距離","km"],liters:["Liters","給油量","L"],count:["Count","給油回数","回"],economy:["Economy","平均燃費","km/L"],price:["Price","平均単価","円/L"],fuelkm:["FuelKm","1km燃料代","円/km"]};Object.keys(map).forEach(k=>document.getElementById("driveCard"+map[k][0]).classList.toggle("active",driveMode===k));driveChartTitle.textContent="月別 "+map[driveMode][1];renderBars(driveBars,vals.map(x=>x[driveMode]),map[driveMode][2])}
function renderBars(el,vals,unit){let numeric=vals.filter(v=>v!==null&&Number.isFinite(+v)),max=Math.max(1,...numeric);el.innerHTML=vals.map((v,i)=>v===null?`<div class="barcol future"><div class="bar-empty"></div><small></small>${i+1}</div>`:`<div class="barcol"><div class="bar" style="height:${Math.max(2,(+v)/max*145)}px" title="${(+v).toFixed((+v)%1?1:0)} ${unit}"></div><small>${v?(+v).toFixed((+v)>=100?0:1):""}</small>${i+1}</div>`).join("")}

function openVehicleManager(){show("vehicles");renderVehicles()}function renderVehicles(){vehicleList.innerHTML=vehicles.map(v=>`<div class="card vehicle-row"><button class="vehicle-select" onclick="selectVehicle('${v.id}')"><div><b>${esc(v.name)} ${v.id===activeId?"✓":""}</b><small>${esc([v.maker,v.model,v.color].filter(Boolean).join(" / "))} ・ ${nf(v.odometer)} km</small></div><span>切替</span></button><button class="vehicle-edit-btn" onclick="openVehicleEdit('${v.id}')">編集</button></div>`).join("")}function selectVehicle(id){activeId=id;localStorage.setItem(KEY.active,id);goHome()}
async function openVehicleEdit(id=null){edit.vehicle=id;let v=id?vehicles.find(x=>x.id===id):null;vehicleEditTitle.textContent=v?"車両を編集":"車両を追加";vehicleDelete.classList.toggle("hidden",!v);editCarName.value=v?.name||"";editCarMaker.value=v?.maker||"";editCarModel.value=v?.model||"";editCarYear.value=v?.year||"";let vc=v?.color||"";if(vc&&!COLOR_LABELS[vc]){let x=vc.toLowerCase();vc=x.includes("白")||x.includes("white")?"white":x.includes("黒")||x.includes("black")?"black":x.includes("銀")||x.includes("silver")?"silver":x.includes("灰")||x.includes("gray")?"gray":x.includes("赤")||x.includes("red")?"red":x.includes("青")||x.includes("blue")?"blue":x.includes("緑")||x.includes("green")?"green":x.includes("黄")||x.includes("yellow")?"yellow":"other"}editCarColor.value=vc;editCarPlate.value=v?.plate||"";editCarKm.value=v?.odometer??"";editCarInspection.value=v?.inspectionDate||"";editCarOil.value=v?.oilInterval||5000;pendingVehiclePhoto=v?.photoId||null;memoDraft=JSON.parse(JSON.stringify(v?.memos||[]));show("vehicleEdit");await renderVehiclePhoto();renderMemoEditor()}
async function saveVehicleEdit(){syncMemoText();let n=editCarName.value.trim(),km=+editCarKm.value;if(!n||km<0)return alert("車両名と走行距離を入力してください。");let data={name:n,maker:editCarMaker.value.trim(),model:editCarModel.value.trim(),year:editCarYear.value.trim(),color:editCarColor.value.trim(),plate:editCarPlate.value.trim(),odometer:km,inspectionDate:editCarInspection.value,oilInterval:+editCarOil.value||5000,photoId:pendingVehiclePhoto,memos:memoDraft};if(edit.vehicle){let i=vehicles.findIndex(x=>x.id===edit.vehicle);vehicles[i]={...vehicles[i],...data}}else{let v={id:uid("vehicle"),...data,createdAt:new Date().toISOString()};vehicles.push(v);activeId=v.id;localStorage.setItem(KEY.active,activeId)}save(KEY.vehicles,vehicles);goHome()}
async function deleteVehicle(){let id=edit.vehicle;if(!id||!confirm("この車両と関連するすべての記録・写真を削除しますか？"))return;let v=vehicles.find(x=>x.id===id);if(v){let ids=[v.photoId,...(v.memos||[]).flatMap(m=>m.photos||[])].filter(Boolean);for(let x of ids)await imageDelete(x)}vehicles=vehicles.filter(v=>v.id!==id);fuelRecords=fuelRecords.filter(r=>r.vehicleId!==id);maintenanceRecords=maintenanceRecords.filter(r=>r.vehicleId!==id);expenseRecords=expenseRecords.filter(r=>r.vehicleId!==id);activeId=vehicles[0]?.id||"";save(KEY.vehicles,vehicles);localStorage.setItem(KEY.active,activeId);persistRecords();activeId?goHome():show("setup")}

function addMemo(){syncMemoText();memoDraft.push({id:uid("memo"),title:"",content:"",photos:[]});renderMemoEditor()}
function syncMemoText(){document.querySelectorAll("[data-memo]").forEach(el=>{let m=memoDraft.find(x=>x.id===el.dataset.memo);if(m)m[el.dataset.field]=el.value})}
function renderMemoEditor(){memoEditor.innerHTML=memoDraft.length?memoDraft.map((m,i)=>`<div class="memo-edit"><div class="memo-number">メモ ${i+1}</div><label>題名<textarea rows="3" data-memo="${m.id}" data-field="title"></textarea></label><label>内容<textarea rows="7" data-memo="${m.id}" data-field="content"></textarea></label><div id="photos_${m.id}" class="photo-grid"></div><div class="photo-actions"><select id="quality_${m.id}"><option value="standard">標準</option><option value="high">高画質</option><option value="original">原画</option></select><label class="file-btn">写真から選択<input type="file" accept="image/*" multiple onchange="addMemoPhotos('${m.id}',event)"></label><label class="file-btn">撮影する<input type="file" accept="image/*" capture="environment" onchange="addMemoPhotos('${m.id}',event)"></label><button type="button" class="danger-mini" onclick="removeMemo('${m.id}')">メモを削除</button></div></div>`).join(""):'<div class="empty-memo">「＋ メモを追加」で新しいメモを作成します。</div>';memoDraft.forEach(m=>{document.querySelector(`[data-memo="${m.id}"][data-field="title"]`).value=m.title||"";document.querySelector(`[data-memo="${m.id}"][data-field="content"]`).value=m.content||"";renderMemoPhotos(m)})}
function removeMemo(id){if(!confirm("このメモと添付写真を削除しますか？"))return;let m=memoDraft.find(x=>x.id===id);Promise.all((m?.photos||[]).map(imageDelete)).then(()=>{memoDraft=memoDraft.filter(x=>x.id!==id);renderMemoEditor()})}
async function addMemoPhotos(id,e){syncMemoText();let m=memoDraft.find(x=>x.id===id),q=document.getElementById("quality_"+id).value;for(let f of [...e.target.files]){let blob=await processImage(f,q),pid=uid("img");await imagePut(pid,blob,{quality:q,name:f.name});m.photos.push(pid)}e.target.value="";renderMemoEditor();updateStorage()}
async function renderMemoPhotos(m){let el=document.getElementById("photos_"+m.id);if(!el)return;el.innerHTML="";for(let pid of m.photos||[]){let rec=await imageGet(pid);if(!rec)continue;let u=URL.createObjectURL(rec.blob),d=document.createElement("div");d.className="photo-tile";d.innerHTML=`<img src="${u}"><button type="button" onclick="removeMemoPhoto('${m.id}','${pid}')">×</button>`;d.querySelector("img").onclick=()=>openImage(u);el.appendChild(d)}}
async function removeMemoPhoto(mid,pid){if(!confirm("この写真をCarLogから削除しますか？"))return;await imageDelete(pid);let m=memoDraft.find(x=>x.id===mid);m.photos=(m.photos||[]).filter(x=>x!==pid);renderMemoPhotos(m);updateStorage()}
async function selectVehiclePhoto(e){let f=e.target.files?.[0];if(!f)return;if(pendingVehiclePhoto)await imageDelete(pendingVehiclePhoto);let blob=await processImage(f,"high"),id=uid("img");await imagePut(id,blob,{quality:"high",name:f.name});pendingVehiclePhoto=id;e.target.value="";renderVehiclePhoto();updateStorage()}
async function removeVehiclePhoto(){if(!pendingVehiclePhoto)return;if(!confirm("車両写真をCarLogから削除しますか？"))return;await imageDelete(pendingVehiclePhoto);pendingVehiclePhoto=null;renderVehiclePhoto();updateStorage()}
function renderVehicleColorPreview(){if(!pendingVehiclePhoto)vehiclePhotoPreview.innerHTML=carSvg(editCarColor.value)}
async function renderVehiclePhoto(){vehiclePhotoPreview.innerHTML=carSvg(editCarColor.value);if(pendingVehiclePhoto){let r=await imageGet(pendingVehiclePhoto);if(r){let u=URL.createObjectURL(r.blob);vehiclePhotoPreview.innerHTML=`<img src="${u}" onclick="openImage('${u}')">`}}}
function openImage(url){let w=window.open();if(w)w.document.write(`<meta name="viewport" content="width=device-width"><body style="margin:0;background:#111;display:grid;place-items:center;min-height:100vh"><img src="${url}" style="max-width:100%;max-height:100vh"></body>`)}

function renderHomeMemos(c){let ms=(c.memos||[]).slice(0,3);homeMemos.innerHTML=ms.length?ms.map(m=>`<button class="memo-home-row" onclick="openVehicleNotes()"><b>${esc(m.title||"無題")}</b><span>${esc((m.content||"").slice(0,70))}</span></button>`).join(""):'<p class="help">車両メモはまだありません。</p>'}
async function openVehicleNotes(){show("vehicleNotes");let c=car(),ms=c?.memos||[];vehicleNotesList.innerHTML=ms.length?ms.map(m=>`<div class="card note-view"><h3>${esc(m.title||"無題")}</h3><div class="note-content">${esc(m.content||"").replace(/\n/g,"<br>")}</div><div id="viewphotos_${m.id}" class="photo-grid"></div></div>`).join(""):'<div class="card">車両メモはありません。</div>';for(let m of ms){let el=document.getElementById("viewphotos_"+m.id);for(let pid of m.photos||[]){let rec=await imageGet(pid);if(!rec)continue;let u=URL.createObjectURL(rec.blob),img=document.createElement("img");img.src=u;img.className="note-photo";img.onclick=()=>openImage(u);el.appendChild(img)}}}
function openSettings(){show("settings");updateStorage()}function openHelp(){show("help")}
function openQuick(){quickBackdrop.classList.remove("hidden")}function closeQuick(e){if(e&&e.target!==quickBackdrop)return;quickBackdrop.classList.add("hidden")}

function idb(){return new Promise((res,rej)=>{let q=indexedDB.open("CarLogDB",1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains("images"))q.result.createObjectStore("images",{keyPath:"id"})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function imagePut(id,blob,meta={}){let db=await idb();return new Promise((res,rej)=>{let tx=db.transaction("images","readwrite");tx.objectStore("images").put({id,blob,...meta,createdAt:new Date().toISOString()});tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function imageGet(id){if(!id)return null;let db=await idb();return new Promise((res,rej)=>{let q=db.transaction("images").objectStore("images").get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function imageDelete(id){if(!id)return;let db=await idb();return new Promise((res,rej)=>{let tx=db.transaction("images","readwrite");tx.objectStore("images").delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function allImages(){let db=await idb();return new Promise((res,rej)=>{let q=db.transaction("images").objectStore("images").getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
async function processImage(file,q){if(q==="original")return file;let max=q==="high"?2400:1600,quality=q==="high"?.92:.82,bmp=await createImageBitmap(file),scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),c=document.createElement("canvas");c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext("2d").drawImage(bmp,0,0,c.width,c.height);return new Promise(r=>c.toBlob(r,"image/jpeg",quality))}
function bytes(n){if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";if(n<1073741824)return(n/1048576).toFixed(1)+" MB";return(n/1073741824).toFixed(2)+" GB"}
async function updateStorage(){if(!document.getElementById("storageTotal"))return;let imgs=await allImages(),imageBytes=imgs.reduce((s,x)=>s+(x.blob?.size||0),0),localBytes=0;for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i),v=localStorage.getItem(k)||"";localBytes+=(k.length+v.length)*2}let total=imageBytes+localBytes;storageTotal.textContent=bytes(total);let extra=`画像 ${bytes(imageBytes)} / その他 ${bytes(localBytes)}`;if(navigator.storage?.estimate){let e=await navigator.storage.estimate();if(e.quota)extra+=` / ブラウザ保存領域の約 ${((e.usage||total)/e.quota*100).toFixed(1)}% 使用`}storageDetail.textContent=extra}

function blobToDataURL(b){return new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b)})}async function dataURLBlob(s){return(await fetch(s)).blob()}
async function exportBackup(withPhotos=false){let data={version:"0.33",exportedAt:new Date().toISOString(),vehicles,activeId,fuelRecords,maintenanceRecords,expenseRecords};if(withPhotos){let imgs=await allImages();data.images=[];for(let x of imgs)data.images.push({id:x.id,quality:x.quality,name:x.name,createdAt:x.createdAt,data:await blobToDataURL(x.blob)})}download(JSON.stringify(data),"CarLog_"+(withPhotos?"Full":"Data")+"_Backup_"+today()+".json","application/json")}
function importBackup(e){let f=e.target.files?.[0];if(!f)return;let rd=new FileReader();rd.onload=async()=>{try{let d=JSON.parse(rd.result);if(!confirm("現在のCarLogデータをバックアップ内容に置き換えますか？"))return;vehicles=d.vehicles||(d.vehicle?[d.vehicle]:[]);activeId=d.activeId||vehicles[0]?.id||"";fuelRecords=d.fuelRecords||[];maintenanceRecords=d.maintenanceRecords||[];expenseRecords=d.expenseRecords||[];save(KEY.vehicles,vehicles);localStorage.setItem(KEY.active,activeId);persistRecords();if(d.images){for(let x of d.images)await imagePut(x.id,await dataURLBlob(x.data),x)}refreshStoreNames();goHome()}catch(err){console.error(err);alert("バックアップファイルを読み込めませんでした。")}};rd.readAsText(f);e.target.value=""}
function csv(v){return'"'+String(v??"").replaceAll('"','""')+'"'}function exportCSV(){let rows=[["車両","種別","日付","時刻","走行距離","内容","店名","金額","燃費","メモ"]];vehicles.forEach(v=>{fuelRecords.filter(r=>r.vehicleId===v.id).forEach(r=>rows.push([v.name,"給油",r.date,r.time,r.odometer,r.liters+" L",r.store||"",r.amount,r.fuelEconomy||"",r.fullTank?"満タン":""]));maintenanceRecords.filter(r=>r.vehicleId===v.id).forEach(r=>rows.push([v.name,"整備・修理",r.date,r.time,r.odometer,r.type,r.store||"",r.amount,"",r.memo||""]));expenseRecords.filter(r=>r.vehicleId===v.id).forEach(r=>rows.push([v.name,"その他支出",r.date,r.time,"",r.category,r.store||"",r.amount,"",r.memo||""]))});download("\uFEFF"+rows.map(r=>r.map(csv).join(",")).join("\r\n"),"CarLog_"+today()+".csv","text/csv;charset=utf-8")}
function download(data,name,type){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
